version: '3'
services:
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_DB=little_big_db
      - POSTGRES_USER=little_big_user
      - POSTGRES_PASSWORD=0f595fea-b2a9-489b
    ports:
      - 54310:5432
    expose:
      - 5432
    networks:
      - backend

networks:
  backend:
    driver: bridge



